/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exercise {
  'id' : string,
  'lessonId' : string,
  'question' : string,
  'explanation' : string,
  'correctAnswer' : string,
  'options' : Array<string>,
}
export interface Lesson {
  'id' : string,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'xpReward' : bigint,
  'description' : string,
  'codeExample' : string,
}
export interface UserProfile {
  'username' : string,
  'userId' : Principal,
  'totalXP' : bigint,
  'completedLessons' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[string], UserProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExercises' : ActorMethod<[string], Array<Exercise>>,
  'getLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'getLesson' : ActorMethod<[string], [] | [Lesson]>,
  'getLessons' : ActorMethod<[], Array<Lesson>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isLessonCompleted' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'submitLessonProgress' : ActorMethod<[string, bigint], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];